<?
$dissalow='User-agent: Googlebot
Disallow: /bitrix/admin/
Disallow: /cgi-bin/
Disallow: /search/
Disallow: /*phrase_id=
Disallow: /*ELEMENT_ID=
Disallow: /*SECTION_ID=
Disallow: /*COUNTRY_ID=
Disallow: /*CITY_ID
Disallow: /*REGION_ID=
Disallow: /*CONTINENT_ID=
Disallow: /*id=
Disallow: /*q=
Disallow: /*lang=
Disallow: /*where=
Disallow: /*date=
Disallow: /*error=
Disallow: /*n=
Disallow: /*swf
Disallow: /*iframe
Disallow: /*?from=direct
Disallow: /*?_pdflist=
Disallow: /*?_openstat
Disallow: /*?gclid=
Disallow: /*?yclid=
Disallow: /*?ymclid=
Disallow: /*utm_source=
Disallow: /*from=adwords
Disallow: /*?cid=
Disallow: /*?frommarket=
Disallow: /redirect.php
Disallow: /o-kompanii/video/company.php
Disallow: /podderzhka/?city=*
Disallow: /registration/?*
Disallow: /o-kompanii/svodnye-dannye-o-rezultatakh-provedeniya-spetsialnoy-otsenki-usloviy-truda.php
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-1.jpg
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-2.jpg
Disallow: /images/svodnye-vedomosti/2/svodnaya-vedomost-sout-28-08-2017.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-1.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-2.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-3.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-1.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-2.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-3.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-5.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-6.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-1.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-1.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-3.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-4.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-5.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-6.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-7.jpg
Disallow: /images/svodnye-vedomosti/8/svodnaya-vedomost-kafe-2018.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-1.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-2.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-3.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-4.jpg

User-agent: bingbot
Disallow: /bitrix/admin/
Disallow: /cgi-bin/
Disallow: /search/
Disallow: /*phrase_id=
Disallow: /*ELEMENT_ID=
Disallow: /*SECTION_ID=
Disallow: /*COUNTRY_ID=
Disallow: /*CITY_ID
Disallow: /*REGION_ID=
Disallow: /*CONTINENT_ID=
Disallow: /*id=
Disallow: /*q=
Disallow: /*lang=
Disallow: /*where=
Disallow: /*date=
Disallow: /*error=
Disallow: /*n=
Disallow: /*swf
Disallow: /*iframe
Disallow: /*?from=direct
Disallow: /*?_pdflist=
Disallow: /*?_openstat
Disallow: /*?gclid=
Disallow: /*?yclid=
Disallow: /*?ymclid=
Disallow: /*utm_source=
Disallow: /*from=adwords
Disallow: /*?cid=
Disallow: /*?frommarket=
Disallow: /redirect.php
Disallow: /o-kompanii/video/company.php
Disallow: /podderzhka/?city=*
Disallow: /registration/?*
Disallow: /o-kompanii/svodnye-dannye-o-rezultatakh-provedeniya-spetsialnoy-otsenki-usloviy-truda.php
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-1.jpg
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-2.jpg
Disallow: /images/svodnye-vedomosti/2/svodnaya-vedomost-sout-28-08-2017.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-1.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-2.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-3.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-1.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-2.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-3.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-5.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-6.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-1.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-1.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-3.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-4.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-5.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-6.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-7.jpg
Disallow: /images/svodnye-vedomosti/8/svodnaya-vedomost-kafe-2018.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-1.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-2.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-3.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-4.jpg

User-agent: *
Disallow: /bitrix/admin/
Disallow: /cgi-bin/
Disallow: /search/
Disallow: /*phrase_id=
Disallow: /*ELEMENT_ID=
Disallow: /*SECTION_ID=
Disallow: /*COUNTRY_ID=
Disallow: /*CITY_ID
Disallow: /*REGION_ID=
Disallow: /*CONTINENT_ID=
Disallow: /*id=
Disallow: /*q=
Disallow: /*lang=
Disallow: /*where=
Disallow: /*date=
Disallow: /*error=
Disallow: /*n=
Disallow: /*swf
Disallow: /*iframe
Disallow: /*?from=direct
Disallow: /*?_pdflist=
Disallow: /*?_openstat
Disallow: /*?gclid=
Disallow: /*?yclid=
Disallow: /*?ymclid=
Disallow: /*utm_source=
Disallow: /*from=adwords
Disallow: /*?cid=
Disallow: /*?frommarket=
Disallow: /redirect.php
Disallow: /o-kompanii/video/company.php
Disallow: /podderzhka/?city=*
Disallow: /registration/?*
Disallow: /o-kompanii/svodnye-dannye-o-rezultatakh-provedeniya-spetsialnoy-otsenki-usloviy-truda.php
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-1.jpg
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-2.jpg
Disallow: /images/svodnye-vedomosti/2/svodnaya-vedomost-sout-28-08-2017.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-1.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-2.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-3.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-1.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-2.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-3.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-5.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-6.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-1.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-1.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-3.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-4.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-5.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-6.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-7.jpg
Disallow: /images/svodnye-vedomosti/8/svodnaya-vedomost-kafe-2018.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-1.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-2.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-3.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-4.jpg
Clean-param: iframe&width&height
Clean-param: utm_source&utm_medium&utm_campaign&utm_content&_openstat
Clean-param: _subscribe
Clean-param: month&year
Host: http://www.perco.ru

User-agent: Yandex
Disallow: /o-kompanii/svodnye-dannye-o-rezultatakh-provedeniya-spetsialnoy-otsenki-usloviy-truda.php
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-1.jpg
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-2.jpg
Disallow: /images/svodnye-vedomosti/2/svodnaya-vedomost-sout-28-08-2017.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-1.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-2.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-3.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-1.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-2.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-3.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-5.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-6.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-1.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-1.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-3.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-4.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-5.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-6.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-7.jpg
Disallow: /images/svodnye-vedomosti/8/svodnaya-vedomost-kafe-2018.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-1.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-2.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-3.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-4.jpg

User-agent: Googlebot-Image
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-1.jpg
Disallow: /images/svodnye-vedomosti/1/svodnaya-vedomost-sout-31-05-2017-2.jpg
Disallow: /images/svodnye-vedomosti/2/svodnaya-vedomost-sout-28-08-2017.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-1.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-2.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-3.jpg
Disallow: /images/svodnye-vedomosti/3/svodnaya-vedomost-sout-20-11-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-1.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-2.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-3.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-4.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-5.jpg
Disallow: /images/svodnye-vedomosti/4/svodnaya-vedomost-sout-25-12-2017-6.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-1.jpg
Disallow: /images/svodnye-vedomosti/5/svodnaya-vedomost-sout-01-08-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-1.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-2.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-3.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-4.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-5.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-6.jpg
Disallow: /images/svodnye-vedomosti/7/svodnaya-vedomost-2018-7.jpg
Disallow: /images/svodnye-vedomosti/8/svodnaya-vedomost-kafe-2018.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-1.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-2.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-3.jpg
Disallow: /images/svodnye-vedomosti/6/svodnaya-vedomost-rezultatov-sout-09-04-2020-4.jpg

Sitemap: http://www.perco.ru/sitemap.xml';
header("Content-type: text/plain");
echo $dissalow;
?>